create table if not exists public.products (
  id bigint generated by default as identity primary key,
  catalog_key text,
  name text not null,
  category text not null,
  price_label text,
  price_ngn bigint,
  image_url text,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.products add column if not exists catalog_key text;
alter table public.products add column if not exists price_label text;
alter table public.products add column if not exists price_ngn bigint;
alter table public.products alter column image_url drop not null;
alter table public.products drop column if exists post_url;
alter table public.products drop column if exists type;
alter table public.products drop column if exists description;
alter table public.products drop column if exists badge;
alter table public.products drop column if exists price_date;
alter table public.products drop constraint if exists products_category_check;
alter table public.products add constraint products_category_check
  check (category in ('Jewellery', 'Bags', 'Watches', 'Eyewear', 'Gift sets'));

alter table public.products enable row level security;

drop policy if exists "Anyone can view active products" on public.products;
create policy "Anyone can view active products"
  on public.products for select
  using (is_active = true);

grant select on public.products to anon, authenticated;

create unique index if not exists products_catalog_key_idx
  on public.products (catalog_key);

update public.products set is_active = false;

insert into public.products (catalog_key, name, category, price_label, price_ngn, image_url, sort_order)
values
  ('piece-01', 'Gold & Silver Choker Set', 'Jewellery', '₦20,500', 20500, '/products/product-01.jpg', 1),
  ('piece-02', 'Gold Choker', 'Jewellery', '₦12,500', 12500, '/products/product-02.jpg', 2),
  ('piece-03', 'Gold Choker Necklace', 'Jewellery', '₦18,000', 18000, '/products/product-03.jpg', 3),
  ('piece-04', 'Gold & Silver Choker', 'Jewellery', '₦15,000', 15000, '/products/product-04.jpg', 4),
  ('piece-05', 'Gold Choker Set', 'Jewellery', '₦18,500', 18500, '/products/product-05.jpg', 5),
  ('piece-06', 'Gold Choker Set', 'Jewellery', '₦18,500', 18500, '/products/product-06.jpg', 6),
  ('piece-07', 'Gold Choker', 'Jewellery', '₦18,000', 18000, '/products/product-07.jpg', 7),
  ('piece-08', 'Gold Choker Set', 'Jewellery', '₦18,000', 18000, '/products/product-08.jpg', 8),
  ('piece-09', 'Silver Statement Earring', 'Jewellery', '₦10,000', 10000, '/products/product-09.jpg', 9),
  ('piece-10', 'Statement Earring', 'Jewellery', '₦9,000', 9000, '/products/product-10.jpg', 10),
  ('piece-11', 'High Zirconia 4-Piece Necklace Set', 'Jewellery', '₦75,000', 75000, '/products/product-11.jpg', 11)
on conflict (catalog_key) do update set
  name = excluded.name,
  category = excluded.category,
  price_label = excluded.price_label,
  price_ngn = excluded.price_ngn,
  image_url = excluded.image_url,
  is_active = true,
  sort_order = excluded.sort_order;